<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>自动化测试报告</title>
    <meta name="generator" content="HTMLTestRunner 1.2.0"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="https://img.hcharts.cn/highcharts/highcharts.js"></script>
    <script src="https://img.hcharts.cn/highcharts/modules/exporting.js"></script>

    <style type="text/css" media="screen">
        body        { font-family: Microsoft YaHei;padding: 20px; font-size: 100%; }
        table       { font-size: 100%; }
        .table tbody tr td{
            vertical-align: middle;
        }

        /* -- heading ---------------------------------------------------------------------- */
        .heading .description, .attribute {
            clear: both;
        }

        /* --- 失败和错误合集样式 -- Gelomen --- */
        .failCollection, .errorCollection {
            width: 100px;
            float: left;
        }
        #failCaseOl li {
            color: red
        }
        #errorCaseOl li {
            color: orange
        }

        /* --- 打开截图特效样式 -- Gelomen --- */
        .data-img{
            cursor:pointer
        }

        .pic_looper{
            width:100%;
            height:100%;
            position: fixed;
            left: 0;
            top:0;
            opacity: 0.6;
            background: #000;
            display: none;
            z-index: 100;
        }

        .pic_show{
            width:100%;
            position:fixed;
            left:0;
            top:0;
            right:0;
            bottom:0;
            margin:auto;
            text-align: center;
            display: none;
            z-index: 100;
        }

        .pic_box{
            padding:10px;
            width:90%;
            height:90%;
            margin:40px auto;
            text-align: center;
            overflow: hidden;
        }

        .pic_box img{
            width: auto;
            height: 100%;
            -moz-box-shadow: 0px 0px 20px 0px #000;
            -webkit-box-shadow: 0px 0px 20px 0px #000;
            box-shadow: 0px 0px 20px 0px #000;
        }

        /* --- 饼状图div样式 -- Gelomen --- */
        #container {
            width: 450px;
            height: 300px;
            float: left;
        }

        /* -- report ------------------------------------------------------------------------ */
        #total_row  { font-weight: bold; }
        .passCase   { color: #5cb85c; }
        .failCase   { color: #d9534f; font-weight: bold; }
        .errorCase  { color: #f0ad4e; font-weight: bold; }
        .hiddenRow  { display: none; }
        .testcase   { margin-left: 2em; }
        .screenshot:link { text-decoration: none;color: deeppink; }
        .screenshot:visited { text-decoration: none;color: deeppink; }
        .screenshot:hover { text-decoration: none;color: darkcyan; }
        .screenshot:active { text-decoration: none;color: deeppink; }
    </style>

</head>
<body >

<?php echo $this->getContent(); ?>


<div id='ending'>&nbsp;</div>
<div id="toTop" style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer; display: none">
    <a><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
</body>
</html>

