<?php $this->partial("common/header"); ?>
<div class="container-fluid">
    <div class="row">
        <?php $this->partial("common/top"); ?>
    </div>
    <div class="row">
        <div class="col-md-3">
            <?php $this->partial("common/left"); ?>
        </div>
        <div class="col-md-9">
            <?php $this->partial("common/right"); ?>
        </div>
    </div>
</div>
<?php $this->partial("common/footer"); ?>


